# Site
repository: floydspace/floydspace.github.io
# favicon: images/favicon.ico

# Personal info
name: Victor Korzunin
title: Software Developer
address: Rotterdam, The Netherlans
website: floydspace.github.io

# Social links
github_username: floydspace
npm_username: f1oyd
facebook_username: f10yd
instagram_username: victor_korzunin
linkedin_username: korzunin

# About Section
about_title: Profile
about_profile_image: images/profile.jpeg
about_content: |
  Formerly I used to be a financial market trader and had been working in financial companies and a bank for 10 years in common. Software Development was one of my hobbies which helped me in my work. Recently I decided to do software development professionally and realized it is what I've desired to be doing.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Hobbies
more_content: |
  Alongside my interests in software development some of my other interests and hobbies are:
   - 🏂 Snowboarding
   - 🗻 Mountain Hiking
   - 🚵 Cycling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
